apiVersion: v1
kind: Service
metadata:
  name: workengine-core-svc
spec:
  selector:
    app: workengine
    component: core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: workengine-dashboard-svc
spec:
  selector:
    app: workengine
    component: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
